CREATE DATABASE IF NOT EXISTS database_max;

USE database_max;

CREATE TABLE IF NOT EXISTS copywriting(
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    cw_name VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS words(
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    cw_id int(255) NOT NULL,
    word VARCHAR(255) NOT NULL,
    CONSTRAINT fk_words FOREIGN KEY (cw_id) REFERENCES copywriting(id)
);

CREATE TABLE IF NOT EXISTS topics(
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    topic_name VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS key_ideas(
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    ki_id int(255) NOT NULL,
    idea VARCHAR(255) NOT NULL,
    CONSTRAINT fk_idea FOREIGN KEY (ki_id) REFERENCES topics(id)
);

CREATE TABLE IF NOT EXISTS page_topic(
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    topic VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS page_notion(
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    notion VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS page_angle(
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    angle VARCHAR(255) NOT NULL
);